### ISSUE TITLE
Can't build - no 'hr_msgs' pkg cfg

### ISSUE THREAD

**Issue by pringithub** [elggem/ros_peoplemodel#7]
-- Could not find the required component 'hr_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "hr_msgs" with any
  of the following names:

    hr_msgsConfig.cmake
    hr_msgs-config.cmake

**Comment by pringithub** [comment]
More of an awareness than an issue. It seems you included two packages in package.xml, CMakeLists.txt [hr_msgs, blender_api_msgs] that most others likely don't have. 

To anyone else, simply delete those lines and you'll be good.

**Comment by elggem** [comment]
Hey just saw this, thanks for your comment! I will be fixing this soon.

**Comment by elggem** [comment]
Fixed!
